
backend:
  name: git-gateway
  branch: main
media_folder: "src/media"
public_folder: "/media"
collections:
  - name: "posts"
    label: "Články"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Popis", name: "description", widget: "string", required: false }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Obsah", name: "body", widget: "markdown" }
  - name: "videos"
    label: "Videá"
    folder: "src/videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Video embed (YouTube/Vimeo)", name: "body", widget: "markdown", hint: "Vlož sem <iframe> kód." }
